import type { Product, Collection } from "./types"

export const collections: Collection[] = [
  {
    id: "1",
    name: "Eterno Verdor",
    slug: "eterno-verdor",
    description: "Colección inspirada en la profundidad y misterio de las esmeraldas colombianas",
    image: "/luxury-emerald-jewelry-collection-dark-elegant.jpg",
    season: "Primavera 2025",
  },
  {
    id: "2",
    name: "Luz de Luna",
    slug: "luz-de-luna",
    description: "Piezas que capturan la elegancia nocturna con diamantes y esmeraldas",
    image: "/moonlight-diamond-emerald-luxury-jewelry.jpg",
    season: "Otoño 2024",
  },
  {
    id: "3",
    name: "Herencia Real",
    slug: "herencia-real",
    description: "Diseños clásicos inspirados en la joyería de la realeza europea",
    image: "/royal-heritage-luxury-gold-emerald-jewelry-crown.jpg",
    season: "Invierno 2024",
  },
  {
    id: "4",
    name: "Aurora Boreal",
    slug: "aurora-boreal",
    description: "Colección moderna con acabados que reflejan los colores del norte",
    image: "/modern-aurora-jewelry-platinum-emerald-luxury.jpg",
    season: "Verano 2025",
  },
]

export const products: Product[] = [
  {
    id: "1",
    sku: "EV-AN-001",
    name: "Anillo Emperatriz",
    description:
      "Anillo de compromiso con esmeralda colombiana de 2.5 quilates, engastada en oro de 18 quilates con diamantes laterales. Una pieza única que representa el más alto estándar de la joyería de lujo.",
    price: 12500000,
    compareAtPrice: 14000000,
    images: ["/luxury-emerald-engagement-ring-gold-diamonds-front.jpg", "/luxury-emerald-ring-side-view-gold.jpg", "/emerald-ring-detail-close-up.jpg"],
    category: "anillos",
    material: "oro-18k",
    gemstone: "esmeralda",
    weight: "8.5g",
    collection: "Eterno Verdor",
    season: "Primavera 2025",
    inStock: true,
    stockQuantity: 3,
    featured: true,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    sku: "EV-CO-002",
    name: "Collar Cascada Esmeralda",
    description:
      "Collar con 12 esmeraldas en cascada, montadas en oro blanco de 18k. Diseño exclusivo que evoca la elegancia de una cascada de piedras preciosas.",
    price: 28750000,
    images: ["/luxury-emerald-cascade-necklace-white-gold-elegant.jpg", "/emerald-necklace-worn-model-elegant.jpg"],
    category: "collares",
    material: "oro-18k",
    gemstone: "esmeralda",
    weight: "45g",
    collection: "Eterno Verdor",
    season: "Primavera 2025",
    inStock: true,
    stockQuantity: 2,
    featured: true,
    createdAt: "2024-01-20",
  },
  {
    id: "3",
    sku: "LL-AR-003",
    name: "Aretes Luz de Luna",
    description:
      "Aretes colgantes con esmeraldas y diamantes, diseño que captura la luz de manera espectacular. Perfectos para ocasiones especiales.",
    price: 8900000,
    images: ["/luxury-emerald-diamond-drop-earrings-elegant.jpg", "/emerald-earrings-close-up-detail.jpg"],
    category: "aretes",
    material: "oro-18k",
    gemstone: "esmeralda",
    weight: "12g",
    collection: "Luz de Luna",
    season: "Otoño 2024",
    inStock: true,
    stockQuantity: 5,
    featured: true,
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    sku: "HR-PU-004",
    name: "Pulsera Herencia Real",
    description:
      "Pulsera de eslabones con 7 esmeraldas colombianas de alta calidad, engastadas en platino. Un tributo a la joyería clásica europea.",
    price: 18500000,
    images: ["/luxury-platinum-emerald-bracelet-royal-design.jpg", "/emerald-bracelet-detail-platinum.jpg"],
    category: "pulseras",
    material: "platino",
    gemstone: "esmeralda",
    weight: "35g",
    collection: "Herencia Real",
    season: "Invierno 2024",
    inStock: true,
    stockQuantity: 2,
    featured: true,
    createdAt: "2024-02-15",
  },
  {
    id: "5",
    sku: "AB-AN-005",
    name: "Anillo Aurora",
    description:
      "Anillo contemporáneo con esmeralda central rodeada de un halo de diamantes, diseño moderno en platino.",
    price: 9750000,
    images: ["/modern-emerald-halo-ring-platinum-diamonds.jpg"],
    category: "anillos",
    material: "platino",
    gemstone: "esmeralda",
    weight: "6.2g",
    collection: "Aurora Boreal",
    season: "Verano 2025",
    inStock: true,
    stockQuantity: 4,
    featured: false,
    createdAt: "2024-03-01",
  },
  {
    id: "6",
    sku: "EV-PE-006",
    name: "Pendiente Gota de Rocío",
    description:
      "Pendiente solitario con esmeralda en forma de gota, montaje en oro de 24 quilates. Simplicidad que habla de lujo.",
    price: 4200000,
    images: ["/teardrop-emerald-pendant-gold-chain-luxury.jpg"],
    category: "pendientes",
    material: "oro-24k",
    gemstone: "esmeralda",
    weight: "5.8g",
    collection: "Eterno Verdor",
    season: "Primavera 2025",
    inStock: true,
    stockQuantity: 8,
    featured: false,
    createdAt: "2024-03-10",
  },
  {
    id: "7",
    sku: "LL-CO-007",
    name: "Gargantilla Noche Estrellada",
    description: "Gargantilla de plata 925 con esmeraldas y diamantes dispuestos como constelaciones.",
    price: 6800000,
    images: ["/placeholder.svg?height=800&width=800"],
    category: "collares",
    material: "plata-925",
    gemstone: "esmeralda",
    weight: "28g",
    collection: "Luz de Luna",
    season: "Otoño 2024",
    inStock: false,
    stockQuantity: 0,
    featured: false,
    createdAt: "2024-03-20",
  },
  {
    id: "8",
    sku: "HR-AR-008",
    name: "Aretes Princesa",
    description:
      "Aretes tipo botón con esmeraldas de corte princesa, rodeadas de micro pavé de diamantes en oro de 18k.",
    price: 7250000,
    images: ["/placeholder.svg?height=800&width=800"],
    category: "aretes",
    material: "oro-18k",
    gemstone: "esmeralda",
    weight: "8g",
    collection: "Herencia Real",
    season: "Invierno 2024",
    inStock: true,
    stockQuantity: 6,
    featured: false,
    createdAt: "2024-04-01",
  },
  {
    id: "9",
    sku: "AB-PU-009",
    name: "Brazalete Infinito",
    description: "Brazalete rígido con diseño de infinito, esmeraldas y diamantes en oro rosa de 18k.",
    price: 11200000,
    images: ["/placeholder.svg?height=800&width=800"],
    category: "pulseras",
    material: "oro-18k",
    gemstone: "esmeralda",
    weight: "22g",
    collection: "Aurora Boreal",
    season: "Verano 2025",
    inStock: true,
    stockQuantity: 3,
    featured: true,
    createdAt: "2024-04-15",
  },
  {
    id: "10",
    sku: "EV-AN-010",
    name: "Anillo Eternity",
    description: "Anillo de eternidad con esmeraldas calibradas en todo el contorno, oro de 18k.",
    price: 15800000,
    images: ["/placeholder.svg?height=800&width=800"],
    category: "anillos",
    material: "oro-18k",
    gemstone: "esmeralda",
    weight: "10g",
    collection: "Eterno Verdor",
    season: "Primavera 2025",
    inStock: true,
    stockQuantity: 2,
    featured: false,
    createdAt: "2024-05-01",
  },
  {
    id: "11",
    sku: "LL-PE-011",
    name: "Colgante Corazón Esmeralda",
    description: "Colgante en forma de corazón con esmeralda central de 1.8 quilates en platino.",
    price: 8400000,
    images: ["/placeholder.svg?height=800&width=800"],
    category: "pendientes",
    material: "platino",
    gemstone: "esmeralda",
    weight: "7.5g",
    collection: "Luz de Luna",
    season: "Otoño 2024",
    inStock: true,
    stockQuantity: 4,
    featured: false,
    createdAt: "2024-05-15",
  },
  {
    id: "12",
    sku: "HR-CO-012",
    name: "Collar Reina Isabel",
    description: "Collar statement con diseño inspirado en joyas de la corona, múltiples esmeraldas y diamantes.",
    price: 45000000,
    compareAtPrice: 52000000,
    images: ["/placeholder.svg?height=800&width=800"],
    category: "collares",
    material: "oro-24k",
    gemstone: "esmeralda",
    weight: "85g",
    collection: "Herencia Real",
    season: "Invierno 2024",
    inStock: true,
    stockQuantity: 1,
    featured: true,
    createdAt: "2024-06-01",
  },
]

export const categoryLabels: Record<string, string> = {
  anillos: "Anillos",
  collares: "Collares",
  aretes: "Aretes",
  pulseras: "Pulseras",
  pendientes: "Pendientes",
}

export const materialLabels: Record<string, string> = {
  "oro-18k": "Oro 18K",
  "oro-24k": "Oro 24K",
  "plata-925": "Plata 925",
  platino: "Platino",
}

export const gemstoneLabels: Record<string, string> = {
  esmeralda: "Esmeralda",
  diamante: "Diamante",
  rubi: "Rubí",
  zafiro: "Zafiro",
  "sin-piedra": "Sin Piedra",
}
